const TYPES = {
  UserRepository: Symbol.for('UserRepository'),
  PasswordHasher: Symbol.for('PasswordHasher'),
  RegisterUserUseCase: Symbol.for('RegisterUserUseCase'),
  TokenVerifier: Symbol.for('TokenVerifier'),
  VerificationTokenRepository: Symbol.for('VerificationTokenRepository'),
  SendVerificationEmailUseCase: Symbol.for('SendVerificationEmailUseCase'),
  EmailService: Symbol.for('EmailService'),
  OTPService: Symbol.for('OTPService'),
  RegisterUserWithMobile: Symbol.for('RegisterUserWithMobile'),
  VerifyOTPUseCase: Symbol.for('VerifyOTPUseCase'),
  SendOTPUseCase: Symbol.for('SendOTPUseCase'),
  CreateDeliveryPartner: Symbol.for('CreateDeliveryPartner'),
  DeliveryPartnerRepository: Symbol.for('DeliveryPartnerRepository'),
  IHashService: Symbol.for('IHashService'),
  IAdminRepository: Symbol.for('IAdminRepository'),
  ISignInAdminUseCase: Symbol.for('ISignInAdminUseCase'),
  IShopOwnerRepository: Symbol.for('IShopOwnerRepository'),
  ISignInShopOwnerUseCase: Symbol.for('ISignInShopOwnerUseCase'),
  ISignUpShopOwnerUseCase: Symbol.for('ISignUpShopOwnerUseCase'),
  ResendVerificationTokenUseCase: Symbol.for('ResendVerificationTokenUseCase'),
  UpdateShopOwnerUseCase: Symbol.for('UpdateShopOwnerUseCase'),
};

export { TYPES };
