name: Deploy Store Hub API to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Enable Corepack and Set up Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.2.2 --activate

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16'

      - name: Install Dependencies
        run: yarn

      - name: Compile TS to JS
        run: yarn tsc || true

      - name: Clear Remote Directory and Deploy Files
        env:
          PEM_KEY: ${{ secrets.EC2_PEM_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          APP_DIRECTORY: "/home/${{ secrets.EC2_USER }}/storehub-api/dist"
        run: |
          echo "$PEM_KEY" > ec2-key.pem
          chmod 600 ec2-key.pem

          # Clean the target directory on the server
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem "$EC2_USER@$EC2_HOST" "rm -rf $APP_DIRECTORY/*"

          # Deploy the dist files to the target directory
          scp -o StrictHostKeyChecking=no -i ec2-key.pem -r ./dist/* "$EC2_USER@$EC2_HOST:$APP_DIRECTORY/"

          # Copy package.json and install only production dependencies using workspaces
          scp -o StrictHostKeyChecking=no -i ec2-key.pem ./package.json "$EC2_USER@$EC2_HOST:/home/${{ secrets.EC2_USER }}/storehub-api/"
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem "$EC2_USER@$EC2_HOST" "cd /home/${{ secrets.EC2_USER }}/storehub-api && yarn workspaces focus --production"

          # Restart the app with pm2
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem "$EC2_USER@$EC2_HOST" "pm2 restart store-hub-api"

      - name: Clean Up
        run: rm -f ec2-key.pem
